
"use client";

import jsPDF from "jspdf";
import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";

interface Scene {
  label: string;
  prompt: string;
  url?: string;
  status: "pending" | "loading" | "loaded" | "failed";
}

interface StoryInfo {
  id: string;
  genre: string;
  premise: string | null;
  blockCount: number;
}

export default function GalleryPage() {
  const params = useParams();
  const router = useRouter();
  const storyId = params.id as string;

  const [scenes, setScenes] = useState<Scene[]>([]);
  const [story, setStory] = useState<StoryInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedImage, setSelectedImage] = useState<number | null>(null);
  const [generating, setGenerating] = useState(false);

  // Step 1: Fetch scene prompts
  useEffect(() => {
    async function fetchGallery() {
      try {
        const res = await fetch(`/api/story/${storyId}/gallery`);
        const data = await res.json();
        if (data.error) throw new Error(data.error);
        setStory(data.story);
        setScenes(data.scenes.map((s: { label: string; prompt: string }) => ({
          ...s,
          status: "pending" as const,
        })));
      } catch (err: unknown) {
        setError(err instanceof Error ? err.message : "Failed to load gallery");
      } finally {
        setLoading(false);
      }
    }
    fetchGallery();
  }, [storyId]);

  // Step 2: Generate images one by one
  useEffect(() => {
    if (scenes.length === 0 || generating) return;
    const pendingScenes = scenes.filter((s) => s.status === "pending");
    if (pendingScenes.length === 0) return;

    setGenerating(true);

    const generateAll = async () => {
      const pendingIndices = scenes
        .map((s, idx) => s.status === "pending" ? idx : -1)
        .filter((idx) => idx !== -1);

      // Process in batches of 2
      for (let i = 0; i < pendingIndices.length; i += 2) {
        const batch = pendingIndices.slice(i, i + 2);
        await Promise.all(batch.map((idx) => generateImage(idx)));
        // Small delay between batches
        if (i + 2 < pendingIndices.length) {
          await new Promise((r) => setTimeout(r, 1000));
        }
      }
      setGenerating(false);
    };

    generateAll();
  }, [scenes.length]);

  const generateImage = async (idx: number, retryPrompt?: string) => {
    const prompt = retryPrompt || scenes[idx]?.prompt;
    if (!prompt) return;

    setScenes((prev) => prev.map((s, i) => i === idx ? { ...s, status: "loading" } : s));

    try {
      const res = await fetch(`/api/story/${storyId}/gallery`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt }),
      });
      const data = await res.json();

      if (data.url) {
        setScenes((prev) => prev.map((s, i) => i === idx ? { ...s, url: data.url, status: "loaded" } : s));
      } else {
        setScenes((prev) => prev.map((s, i) => i === idx ? { ...s, status: "failed" } : s));
      }
    } catch {
      setScenes((prev) => prev.map((s, i) => i === idx ? { ...s, status: "failed" } : s));
    } finally {
      // Check if all are done
    }
  };

  const retryImage = (idx: number) => {
    const prompt = scenes[idx]?.prompt;
    if (!prompt) return;
    setScenes((prev) => prev.map((s, i) => i === idx ? { ...s, status: "pending" } : s));
    setTimeout(() => generateImage(idx, prompt), 100);
  };

  const downloadPDF = async () => {
    const loadedScenes = scenes.filter((s) => s.status === "loaded" && s.url);
    if (!loadedScenes.length || !story) return;

    // Fetch story text
    const res = await fetch(`/api/story/${storyId}/pdf`);
    const data = await res.json();
    if (data.error) return;

    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const textW = pageW - margin * 2;

    // Title page
    pdf.setFillColor(6, 6, 10);
    pdf.rect(0, 0, pageW, pageH, "F");

    pdf.setTextColor(245, 240, 235);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(36);
    const genre = story.genre.charAt(0).toUpperCase() + story.genre.slice(1);
    pdf.text(genre + " Story", pageW / 2, pageH / 3, { align: "center" });

    if (story.premise) {
      pdf.setFontSize(14);
      pdf.setTextColor(124, 58, 237);
      const premiseLines = pdf.splitTextToSize(story.premise, textW);
      pdf.text(premiseLines, pageW / 2, pageH / 3 + 20, { align: "center" });
    }

    pdf.setFontSize(10);
    pdf.setTextColor(90, 86, 100);
    pdf.text("Generated by LLM Story Writer", pageW / 2, pageH - 30, { align: "center" });
    pdf.text(`${data.blocks.length} blocks · ${loadedScenes.length} illustrations`, pageW / 2, pageH - 22, { align: "center" });

    // Helper to add images
    const loadImage = (url: string): Promise<string> => {
      return new Promise((resolve, reject) => {
        const img = new Image();
        img.crossOrigin = "anonymous";
        img.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext("2d");
          if (!ctx) return reject("No canvas context");
          ctx.drawImage(img, 0, 0);
          resolve(canvas.toDataURL("image/jpeg", 0.85));
        };
        img.onerror = () => reject("Image load failed");
        img.src = url;
      });
    };

    // Add opening image as full page
    if (loadedScenes[0]?.url) {
      try {
        const imgData = await loadImage(loadedScenes[0].url!);
        pdf.addPage();
        pdf.setFillColor(6, 6, 10);
        pdf.rect(0, 0, pageW, pageH, "F");

        const imgW = pageW;
        const imgH = (imgW * 9) / 16;
        const imgY = (pageH - imgH) / 2;
        pdf.addImage(imgData, "JPEG", 0, imgY, imgW, imgH);

        // Label overlay
        pdf.setFontSize(10);
        pdf.setTextColor(124, 58, 237);
        pdf.text("OPENING", margin, imgY + imgH + 10);
      } catch (e) {
        console.error("Failed to add opening image:", e);
      }
    }

    // Story text pages with images
    let y = 0;
    const lineHeight = 6;
    const imgLabels = ["", "Plot I", "Plot II", "Plot III", "Climax"];

    for (let bIdx = 0; bIdx < data.blocks.length; bIdx++) {
      const block = data.blocks[bIdx];

      // New page for each block
      pdf.addPage();
      pdf.setFillColor(6, 6, 10);
      pdf.rect(0, 0, pageW, pageH, "F");
      y = margin;

      // Block header
      pdf.setFontSize(9);
      pdf.setTextColor(75, 69, 86);
      pdf.text(`Block ${String(block.blockNum).padStart(2, "0")} · ${block.modelName}`, margin, y);
      y += 10;

      // Story text
      pdf.setFontSize(11);
      pdf.setTextColor(200, 196, 191);
      pdf.setFont("helvetica", "normal");

      const paragraphs = block.text.split("\n\n").filter((p: string) => p.trim());

      for (let pIdx = 0; pIdx < paragraphs.length; pIdx++) {
        const lines = pdf.splitTextToSize(paragraphs[pIdx].trim(), textW);

        for (const line of lines) {
          if (y > pageH - margin) {
            pdf.addPage();
            pdf.setFillColor(6, 6, 10);
            pdf.rect(0, 0, pageW, pageH, "F");
            y = margin;
            pdf.setFontSize(11);
            pdf.setTextColor(200, 196, 191);
          }
          pdf.text(line, margin, y);
          y += lineHeight;
        }
        y += 4; // paragraph gap
      }
    }

    // Image pages for remaining scenes
    for (let sIdx = 1; sIdx < loadedScenes.length; sIdx++) {
      if (!loadedScenes[sIdx]?.url) continue;
      try {
        const imgData = await loadImage(loadedScenes[sIdx].url!);
        pdf.addPage();
        pdf.setFillColor(6, 6, 10);
        pdf.rect(0, 0, pageW, pageH, "F");

        const imgW = pageW;
        const imgH = (imgW * 9) / 16;
        const imgY = (pageH - imgH) / 2;
        pdf.addImage(imgData, "JPEG", 0, imgY, imgW, imgH);

        pdf.setFontSize(10);
        pdf.setTextColor(124, 58, 237);
        pdf.text(imgLabels[sIdx]?.toUpperCase() || `SCENE ${sIdx + 1}`, margin, imgY + imgH + 10);
      } catch (e) {
        console.error(`Failed to add image ${sIdx}:`, e);
      }
    }

    // Footer page
    pdf.addPage();
    pdf.setFillColor(6, 6, 10);
    pdf.rect(0, 0, pageW, pageH, "F");
    pdf.setFontSize(18);
    pdf.setTextColor(245, 240, 235);
    pdf.text("The End", pageW / 2, pageH / 2, { align: "center" });
    pdf.setFontSize(10);
    pdf.setTextColor(42, 42, 58);
    pdf.text("Powered by LLM Story Writer", pageW / 2, pageH / 2 + 12, { align: "center" });

    // Save
    const filename = `story-${story.genre}-${storyId.slice(0, 8)}.pdf`;
    pdf.save(filename);
  };

  const loadedCount = scenes.filter((s) => s.status === "loaded").length;

  const labelColors: Record<string, string> = {
    Opening: "#3B82F6",
    "Plot I": "#F97316",
    "Plot II": "#10B981",
    "Plot III": "#8B5CF6",
    Climax: "#EF4444",
  };

  return (
    <div style={{ minHeight: "100vh", background: "#06060A", color: "#E8E4DF", fontFamily: "'Libre Franklin', system-ui, sans-serif" }}>
      {/* Header */}
      <header style={{
        position: "sticky", top: 0, zIndex: 100, padding: "14px 28px",
        background: "rgba(6,6,10,0.92)", backdropFilter: "blur(20px)",
        borderBottom: "1px solid #ffffff06",
        display: "flex", justifyContent: "space-between", alignItems: "center",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 20, fontWeight: 700, color: "#F5F0EB" }}>LLM</span>
          <span style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 20, fontWeight: 300, color: "#7C3AED", fontStyle: "italic" }}>Story Gallery</span>
        </div>
        <button onClick={() => window.close()} style={{
          background: "none", border: "1px solid #1A1A28", borderRadius: 8,
          padding: "7px 16px", cursor: "pointer", color: "#6B6775", fontSize: 12,
        }}>
          ✕ Close Tab
        </button>
      </header>

      <div style={{ maxWidth: 1000, margin: "0 auto", padding: "40px 24px 120px" }}>
        {/* Loading prompts */}
        {loading && (
          <div style={{ textAlign: "center", padding: "80px 0" }}>
            <div style={{
              width: 32, height: 32, border: "3px solid #7C3AED25",
              borderTop: "3px solid #7C3AED", borderRadius: "50%",
              animation: "spin 0.8s linear infinite", margin: "0 auto 20px",
            }} />
            <div style={{ fontFamily: "'Cormorant Garamond', Georgia, serif", fontSize: 18, color: "#5A5664", fontStyle: "italic" }}>
              Analyzing your story for key visual moments...
            </div>
          </div>
        )}

        {/* Error */}
        {error && (
          <div style={{ textAlign: "center", padding: "80px 0" }}>
            <div style={{ color: "#EF4444", fontSize: 16, marginBottom: 16 }}>{error}</div>
            <button onClick={() => window.close()} style={{
              background: "#7C3AED", border: "none", borderRadius: 8,
              padding: "10px 24px", color: "#fff", cursor: "pointer",
            }}>Close</button>
          </div>
        )}

        {/* Gallery */}
        {!loading && !error && story && (
          <>
            {/* Title */}
            <div style={{ textAlign: "center", marginBottom: 48 }}>
              <div style={{ fontSize: 11, letterSpacing: 5, textTransform: "uppercase", color: "#7C3AED", fontWeight: 600, marginBottom: 14 }}>
                Story Illustrations
              </div>
              <h1 style={{
                fontFamily: "'Cormorant Garamond', Georgia, serif",
                fontSize: "clamp(28px, 5vw, 48px)", fontWeight: 300,
                lineHeight: 1.1, color: "#F5F0EB", marginBottom: 12,
              }}>
                {story.genre.charAt(0).toUpperCase() + story.genre.slice(1)} Story
              </h1>
              {story.premise && (
                <p style={{ fontSize: 14, color: "#4B4556", maxWidth: 500, margin: "0 auto", fontStyle: "italic", lineHeight: 1.6 }}>
                  {story.premise}
                </p>
              )}
              <div style={{ fontSize: 11, color: "#2A2A3A", marginTop: 12 }}>
                {story.blockCount} block{story.blockCount > 1 ? "s" : ""} · 5 illustrations · ~$0.20
              </div>
            </div>

            {/* Progress */}
            <div style={{ marginBottom: 40 }}>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8 }}>
                <span style={{ fontSize: 10, color: "#2A2A3A", letterSpacing: 2, textTransform: "uppercase" }}>
                  {loadedCount < scenes.length ? "Generating illustrations..." : "All illustrations complete"}
                </span>
                <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: "#3A3644" }}>
                  {loadedCount} / {scenes.length}
                </span>
              </div>
              <div style={{ height: 2, background: "#14141F", borderRadius: 1 }}>
                <div style={{
                  height: 2, background: "#7C3AED", borderRadius: 1,
                  width: `${(loadedCount / Math.max(scenes.length, 1)) * 100}%`,
                  transition: "width 0.5s ease",
                }} />
              </div>
            </div>

            {/* Images */}
            <div style={{ display: "flex", flexDirection: "column", gap: 32 }}>
              {scenes.map((scene, idx) => (
                <div key={idx}>
                  {/* Label */}
                  <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 12 }}>
                    <div style={{
                      width: 28, height: 28, borderRadius: "50%",
                      background: `${labelColors[scene.label] || "#7C3AED"}20`,
                      display: "flex", alignItems: "center", justifyContent: "center",
                      fontSize: 12, fontWeight: 700, color: labelColors[scene.label] || "#7C3AED",
                    }}>
                      {idx + 1}
                    </div>
                    <div style={{ fontSize: 14, fontWeight: 600, color: "#E8E4DF" }}>
                      {scene.label}
                    </div>
                    {scene.status === "loading" && (
                      <div style={{
                        width: 12, height: 12,
                        border: `2px solid ${labelColors[scene.label] || "#7C3AED"}30`,
                        borderTop: `2px solid ${labelColors[scene.label] || "#7C3AED"}`,
                        borderRadius: "50%", animation: "spin 0.8s linear infinite",
                      }} />
                    )}
                  </div>

                  {/* Image container */}
                  <div style={{
                    borderRadius: 16, overflow: "hidden",
                    border: `1px solid ${scene.status === "loaded" ? "#1A1A28" : "#14141F"}`,
                    background: "#0A0A14", position: "relative",
                    cursor: scene.status === "loaded" ? "pointer" : "default",
                    aspectRatio: "16/9",
                  }}
                    onClick={() => scene.status === "loaded" && setSelectedImage(idx)}
                  >
                    {/* Pending / Loading */}
                    {(scene.status === "pending" || scene.status === "loading") && (
                      <div style={{
                        position: "absolute", inset: 0,
                        display: "flex", alignItems: "center", justifyContent: "center",
                        flexDirection: "column", gap: 12,
                      }}>
                        {scene.status === "loading" ? (
                          <>
                            <div style={{
                              width: 24, height: 24,
                              border: `2px solid ${labelColors[scene.label] || "#7C3AED"}30`,
                              borderTop: `2px solid ${labelColors[scene.label] || "#7C3AED"}`,
                              borderRadius: "50%", animation: "spin 0.8s linear infinite",
                            }} />
                            <div style={{ fontSize: 12, color: "#3A3644" }}>
                              Generating {scene.label.toLowerCase()}...
                            </div>
                          </>
                        ) : (
                          <div style={{ fontSize: 12, color: "#2A2A3A" }}>Waiting...</div>
                        )}
                      </div>
                    )}

                    {/* Failed */}
                    {scene.status === "failed" && (
                      <div style={{
                        position: "absolute", inset: 0,
                        display: "flex", alignItems: "center", justifyContent: "center",
                        flexDirection: "column", gap: 12,
                      }}>
                        <div style={{ fontSize: 13, color: "#4B4556" }}>Failed to generate</div>
                        <button
                          onClick={(e) => { e.stopPropagation(); retryImage(idx); }}
                          style={{
                            background: "#7C3AED20", border: "1px solid #7C3AED40",
                            borderRadius: 8, padding: "8px 20px", cursor: "pointer",
                            color: "#7C3AED", fontSize: 12, fontWeight: 500,
                          }}
                        >
                          Retry
                        </button>
                      </div>
                    )}

                    {/* Loaded image */}
                    {scene.status === "loaded" && scene.url && (
                      <>
                        <img
                          src={scene.url}
                          alt={`${scene.label} illustration`}
                          style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }}
                        />
                        <div style={{
                          position: "absolute", bottom: 0, left: 0, right: 0,
                          background: "linear-gradient(transparent, rgba(6,6,10,0.9))",
                          padding: "32px 16px 12px",
                          display: "flex", justifyContent: "space-between", alignItems: "flex-end",
                        }}>
                          <div style={{
                            fontSize: 10, color: labelColors[scene.label] || "#7C3AED",
                            letterSpacing: 3, textTransform: "uppercase", fontWeight: 600,
                          }}>
                            {scene.label}
                          </div>
                          <div style={{ fontSize: 9, color: "#2A2A3A" }}>Click to expand</div>
                        </div>
                      </>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* Done */}
            {loadedCount === scenes.length && scenes.length > 0 && (
              <div style={{ textAlign: "center", marginTop: 48 }}>
                <div style={{ height: 1, background: "linear-gradient(90deg, transparent, #7C3AED30, transparent)", marginBottom: 24 }} />
                <div style={{
                  fontFamily: "'Cormorant Garamond', Georgia, serif",
                  fontSize: 15, color: "#5A5664", fontStyle: "italic", marginBottom: 20,
                }}>
                  All illustrations generated
                </div>
                <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
                  <button onClick={downloadPDF} style={{
                    background: "#7C3AED", border: "none", borderRadius: 12,
                    padding: "14px 32px", color: "#fff", fontSize: 14,
                    fontWeight: 600, cursor: "pointer", boxShadow: "0 0 30px #7C3AED20",
                    display: "flex", alignItems: "center", gap: 8,
                  }}>
                    Download Story PDF
                  </button>
                  <button onClick={() => window.close()} style={{
                    background: "none", border: "1px solid #1A1A28", borderRadius: 12,
                    padding: "14px 32px", color: "#6B6775", fontSize: 14,
                    fontWeight: 500, cursor: "pointer",
                  }}>
                    ✕ Close Gallery
                  </button>
                </div>
              </div>
            )}
          </>
        )}
      </div>

      {/* Fullscreen lightbox */}
      {selectedImage !== null && scenes[selectedImage] && (
        <div
          onClick={() => setSelectedImage(null)}
          style={{
            position: "fixed", inset: 0, zIndex: 1000,
            background: "rgba(6,6,10,0.95)", backdropFilter: "blur(20px)",
            display: "flex", alignItems: "center", justifyContent: "center",
            cursor: "pointer", padding: 24,
          }}
        >
          <div style={{ maxWidth: "90vw", maxHeight: "90vh", position: "relative" }}>
            <img
              src={scenes[selectedImage].url}
              alt={scenes[selectedImage].label}
              style={{ maxWidth: "100%", maxHeight: "85vh", borderRadius: 12, display: "block" }}
            />
            <div style={{
              textAlign: "center", marginTop: 12,
              fontSize: 12, color: "#5A5664", letterSpacing: 2, textTransform: "uppercase",
            }}>
              {scenes[selectedImage].label} · Click anywhere to close
            </div>
          </div>

          {selectedImage > 0 && (
            <button
              onClick={(e) => { e.stopPropagation(); setSelectedImage(selectedImage - 1); }}
              style={{
                position: "absolute", left: 20, top: "50%", transform: "translateY(-50%)",
                background: "#1A1A2880", border: "1px solid #2A2A3A", borderRadius: "50%",
                width: 44, height: 44, cursor: "pointer", color: "#E8E4DF",
                fontSize: 18, display: "flex", alignItems: "center", justifyContent: "center",
              }}
            >‹</button>
          )}
          {selectedImage < scenes.length - 1 && (
            <button
              onClick={(e) => { e.stopPropagation(); setSelectedImage(selectedImage + 1); }}
              style={{
                position: "absolute", right: 20, top: "50%", transform: "translateY(-50%)",
                background: "#1A1A2880", border: "1px solid #2A2A3A", borderRadius: "50%",
                width: 44, height: 44, cursor: "pointer", color: "#E8E4DF",
                fontSize: 18, display: "flex", alignItems: "center", justifyContent: "center",
              }}
            >›</button>
          )}
        </div>
      )}
    </div>
  );
}